//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaylistEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mess {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mess() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlaylistEditor.Properties.Mess", typeof(Mess).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument out of range error. Wrong format..
        /// </summary>
        public static string Argument_out_of_range_error__Wrong_format {
            get {
                return ResourceManager.GetString("Argument out of range error. Wrong format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string Cell {
            get {
                return ResourceManager.GetString("Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy/Paste.
        /// </summary>
        public static string Copy_Paste {
            get {
                return ResourceManager.GetString("Copy/Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete List?.
        /// </summary>
        public static string Delete_List {
            get {
                return ResourceManager.GetString("Delete List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your current playlist?.
        /// </summary>
        public static string Do_you_want_to_save_your_current_playlist {
            get {
                return ResourceManager.GetString("Do you want to save your current playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Error.
        /// </summary>
        public static string File_Error {
            get {
                return ResourceManager.GetString("File Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has wrong format or does not exist!   .
        /// </summary>
        public static string File_has_wrong_format_or_does_not_exist_ {
            get {
                return ResourceManager.GetString("File has wrong format or does not exist!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key press.
        /// </summary>
        public static string Key_press {
            get {
                return ResourceManager.GetString("Key press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key press operation failed. .
        /// </summary>
        public static string Key_press_operation_failed {
            get {
                return ResourceManager.GetString("Key press operation failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodi not responding..
        /// </summary>
        public static string Kodi_not_responding {
            get {
                return ResourceManager.GetString("Kodi not responding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodi response: ERROR.
        /// </summary>
        public static string Kodi_response__ERROR {
            get {
                return ResourceManager.GetString("Kodi response: ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodi response: OK.
        /// </summary>
        public static string Kodi_response__OK {
            get {
                return ResourceManager.GetString("Kodi response: OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List import......
        /// </summary>
        public static string List_import {
            get {
                return ResourceManager.GetString("List import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs restart to take effect.
        /// </summary>
        public static string Needs_restart_to_take_effect {
            get {
                return ResourceManager.GetString("Needs restart to take effect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection found!.
        /// </summary>
        public static string No_internet_connection_found {
            get {
                return ResourceManager.GetString("No internet connection found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste operation failed..
        /// </summary>
        public static string Paste_operation_failed {
            get {
                return ResourceManager.GetString("Paste operation failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist Saved.
        /// </summary>
        public static string Playlist_Saved {
            get {
                return ResourceManager.GetString("Playlist Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin links only work in Kodi.
        /// </summary>
        public static string Plugin_links_only_work_in_Kodi {
            get {
                return ResourceManager.GetString("Plugin links only work in Kodi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload File?.
        /// </summary>
        public static string Reload_File {
            get {
                return ResourceManager.GetString("Reload File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Playlist.
        /// </summary>
        public static string Save_Playlist {
            get {
                return ResourceManager.GetString("Save Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Clipboard could not be accessed. Please try again..
        /// </summary>
        public static string The_Clipboard_could_not_be_accessed__Please_try_again {
            get {
                return ResourceManager.GetString("The Clipboard could not be accessed. Please try again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data you pasted is in the wrong format for the cell.
        /// </summary>
        public static string The_data_you_pasted_is_in_the_wrong_format_for_the_cell {
            get {
                return ResourceManager.GetString("The data you pasted is in the wrong format for the cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-Agent links only work in Kodi.
        /// </summary>
        public static string User_Agent_links_only_work_in_Kodi {
            get {
                return ResourceManager.GetString("User-Agent links only work in Kodi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLC player not found.
        /// </summary>
        public static string VLC_player_not_found {
            get {
                return ResourceManager.GetString("VLC player not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong data structure!.
        /// </summary>
        public static string Wrong_data_structure {
            get {
                return ResourceManager.GetString("Wrong data structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong format..
        /// </summary>
        public static string Wrong_format {
            get {
                return ResourceManager.GetString("Wrong format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong input!.
        /// </summary>
        public static string Wrong_input {
            get {
                return ResourceManager.GetString("Wrong input", resourceCulture);
            }
        }
    }
}
